---
apiVersion: v1
kind: Service
metadata:
  namespace: oscar
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP 
  selector:
    app: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: oscar
  name: postgres
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: oscar
  name: postgres
spec:
  replicas: 1
  serviceName: postgres-service
  selector:
    matchLabels:
      service: postgres-service
      app: postgres
  template:
    metadata:
      labels:
        service: postgres-service
        app: postgres
    spec:
      serviceAccountName: postgres
      imagePullSecrets:
        - name: regcred
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: oscar_django
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          # only listen on loopback so only access is via connect proxy
          args: ["-c", "listen_addresses=0.0.0.0"]
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              subPath: data
              name: "pgdata"
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        storageClassName: default-storageclass
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
